language: node_js
sudo: required
dist: trusty

branches:
  only:
    - master
    - /^rc-.*$/
    - /^[0-9]+\.[0-9]+\.[0-9]+.*/

git:
  depth: 10

after_success:
  - bash <(curl -s https://codecov.io/bash)